_commit: v1.2.0
_src_path: https://github.com/ff-fab/tmpl_python_project_kickstart
author_email: mail@fabiankoerner.com
author_name: Fabian Koerner
codecov: true
coverage_threshold: 80
description: An app to read a domestic gas meter using a digital magnetometer.
docs_style: user-journey
github_org: ff-fab
init_git_on_copy: true
license: MIT
module_name: gas2mqtt
project_name: gas2mqtt
release_please: true
repo_name: gas2mqtt
robot_framework: false
